// words.js

export const WORD_LIST = [
  // A - B
  "ABACAXI", "ACADEMIA", "ACAMPAMENTO", "ADVOGADO", "AEROPORTO",
  "ALMOFADA", "AMENDOIM", "ARQUITETO", "ASTRONAUTA", "AZEITONA",
  "BANHEIRO", "BATERIA", "BIBLIOTECA", "BICICLETA", "BISCOITO",
  "BORBOLETA", "BRINQUEDO", "CACHOEIRA", "CACHORRO", "CADEADO",

  // C - D
  "CAMISETA", "CARANGUEJO", "CARNAVAL", "CASTELO", "CAVALEIRO",
  "CELULAR", "CHOCOLATE", "CHURRASCO", "CIENTISTA", "COBERTOR",
  "COMPUTADOR", "CORRIDA", "COZINHEIRO", "DENTISTA", "DESENHO",
  "DIAMANTE", "DINOSSAURO", "DIRETOR", "DOCUMENTO", "EDUCADOR",

  // E - G
  "ELEFANTE", "ELEVADOR", "EMPRESA", "ENGENHEIRO", "ESCALADA",
  "ESMERALDA", "ESPELHO", "ESTUDANTE", "FAZENDA", "FECHADURA",
  "FERRAMENTA", "FLORESTA", "FOGUETE", "FOTOGRAFIA", "FRIGIDEIRA",
  "GABINETE", "GARAGEM", "GELADEIRA", "GOLFINHO", "GUERREIRO",

  // G - M
  "GUITARRA", "HOMEM", "HOSPITAL", "IMPRESSORA", "INSTRUMENTO",
  "INTERNET", "JARDINEIRO", "JOGADOR", "LABIRINTO", "LAPISEIRA",
  "LITERATURA", "MACACO", "MADRUGADA", "MARAVILHA", "MARGARIDA",
  "MENSAGEM", "MICROFONE", "MONTANHA", "MOTORISTA", "NATUREZA",

  // N - S
  "NAVIO", "OCEANO", "ORQUESTRA", "PAPAGAIO", "PASSARELA",
  "PINGUIM", "QUADRO", "QUANTIDADE", "RATOEIRA", "RESTAURANTE",
  "SABONETE", "TARTARUGA", "TELEFONE", "UNIVERSO", "VELOCIDADE",
  "VENTILADOR", "VESTIDO", "XADREZ", "ZANGADO", "ABELHA",

  // Extras variados
  "ABRIGO", "BASCULANTE", "CADEIRA", "DOMINGO", "ENVELOPE",
  "FORMIGA", "GAFANHOTO", "HISTORIA", "INVERNO", "JUVENTUDE",
  "LARGATIXA", "MERCADO", "NOVIDADE", "ORGULHO", "PIMENTA",
  "QUEIJO", "RELOGIO", "SAPATO", "TECLADO", "VASSOURA"
];
